### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by eveevec** [WilliamWelsh/TimeBot#2]
Our time bot on our discord server stopped working. I even deleted and added it again and it still won’t work. Please help.

**Comment by WilliamWelsh** [comment]
The bot is back online and should be working for you. Sorry, I have a master bot that is supposed to tell me when one of my bots goes offline and automatically restart it, but it didn't for some reason. Sorry for the inconvenience.

**Comment by edgicat** [comment]
Hi, times are being reported 4 hours ahead since bit has been restarted.
Also has the discord channel been closed?
Invite on webpage is invalid.

**Comment by eveevec** [comment]
Yes we noticed the times were off but we just updated our times again and I’m not sure what discord channel you mean? 

Eva M. Bocanegra

**Comment by WilliamWelsh** [comment]
Hi, I apologize for all the inconvenience. All my bots are on a new virtual server, and I hadn't noticed that the time on the server was different because the Time Bot uses the servers current time, if you changed your time I will need you to change it back because the bot is on a couple hundred servers and I would rather you guys change yours back then have all those people change them again. As for the server link, I'll fix that soon. If you want to add me my Discord is Reverse#0001.

**Comment by edgicat** [comment]
Thankfully we've not changed our times. I have 50ish people that would need to change their time and there's no way that I can adjust for them
